### ISSUE TITLE
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.RenderTarget' object has no attribute 'read_frame_rgba_gpu'

### ISSUE THREAD

**Issue by Xie-Nav** [ggeorgak11/CM2#5]
hi hello！ I ran this code as you suggested   (python main.py --name test_cm2-gt_val-seen --root_path /path/to/habitat-lab/folder/ --scenes_dir /habitat-lab/data/scene_datasets/ --model_exp_dir /path/to/cm2-gt/model/folder/ --log_dir logs/ --scenes_list 1pXnuDYAj8r --gpu_capacity 1 --split val_seen --use_first_waypoint --vln),  but i got the error as below：

multiprocessing.pool.RemoteTraceback: 

"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/vlnce/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/anaconda3/envs/vlnce/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "main.py", line 21, in nav_testing
    tester.test_navigation()
  File "/test/online_Nav/CM2-master/tester.py", line 110, in test_navigation
    self.test_ds.sim.reset()
  File "/test/datasets/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 326, in reset
    sim_obs = super().reset()
  File "/root/anaconda3/envs/vlnce/lib/python3.7/site-packages/habitat_sim/simulator.py", line 173, in reset
    obs = self.get_sensor_observations(agent_ids=agent_ids)
  File "/root/anaconda3/envs/vlnce/lib/python3.7/site-packages/habitat_sim/simulator.py", line 350, in get_sensor_observations
    agent_observations[sensor_uuid] = sensor.get_observation()
  File "/root/anaconda3/envs/vlnce/lib/python3.7/site-packages/habitat_sim/simulator.py", line 605, in get_observation
    tgt.read_frame_rgba_gpu(self._buffer.data_ptr())  # type: ignore[attr-defined]
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.RenderTarget' object has no attribute 'read_frame_rgba_gpu'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 45, in <module>
    pool.starmap(nav_testing, args)
  File "/root/anaconda3/envs/vlnce/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/root/anaconda3/envs/vlnce/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value

Please, how should I solve it, Thanks!

**Comment by ggeorgak11** [comment]
The error happens on a call to the habitat simulator. Can you verify that you followed our instructions for installing the right versions of habitat-lab and habitat-sim?

**Comment by Xie-Nav** [comment]
> The error happens on a call to the habitat simulator. Can you verify that you followed our instructions for installing the right versions of habitat-lab and habitat-sim?



> The error happens on a call to the habitat simulator. Can you verify that you followed our instructions for installing the right versions of habitat-lab and habitat-sim?

yes, I installed v0.1.7 version

**Comment by daiguangzhao** [comment]
I hvae addressed this problems, i.e., installation of --with-cuda habitat-sim, as follows,

1) git clone --recursive --branch v0.1.7 https://github.com/facebookresearch/habitat-sim.git
2) cd habitat-sim
3) python setup.py install --headless --with-cuda --user
